# Used to login to the testing server with flask
[NETWORK]
URL="http://127.0.0.1:50"
Backend="f_Playwright"

[[ACTION]]
action="text"
name="username"
value="paul"


[[ACTION]]
action="text"
id="ps"
value="123Sasquatch"

[[ACTION]]
action="click"
type="checkbox"

[[ACTION]]
action="click"
name="submit"

[[ACTION]]
action="wait"
wait=5

[[ACTION]]
action="print"