
[NETWORK]
URL="http://127.0.0.1:5000/"
Backend="f_v_Playwright"

[[ACTION]]
action="text"
name="username"
value="paul"

[[ACTION]]
action="text"
id="password"
value="123Sasquatch"

[[ACTION]]
action="click"
xpath='//*[@id="ck"]'

[[ACTION]]
action="click"
type='submit'

[[ACTION]]
action="wait"
wait=20