[NETWORK]
#if set, will cause an error to occur if the SSID does not match 
SSID="examplewifi" 
#overrides the default starting URL for the capture portal. 
URL="https://example.com" #IMPORTANT: Additionally this is (needed for keyring functionality)
#IP address of the Capture Portal 
IP="1.0.0.1"

[[ACTION]] #ID is unique
action="click"
id="example" #ID supports regular expressions


[[ACTION]] #IMPORTANT: can select many (as there can be many with results from a xpath)
action="click"
#the x-path of the respective element(s) that you desire to select
x-path="/html/body/div/div/main/div/p[81]"


[[ACTION]] #IMPORTANT: can select many (as there can be many with name)
action="click"
#the name of the respective element that you desire to select as well as their pos in the webpage
name="examplename" 


[[ACTION]] #can select many (as there can be many with same type)
action="click"
#the type of the respective element(s) that you desire to select 
type="checkbox"

[[ACTION]]
action="wait"
wait=30 #will wait 30 seconds before proceeding

[[ACTION]]
action="text" # will enter text into a field or value
name="name"
#string to automatically enter into the field.
#if not present will prompt the user for one

[[ACTION]]
action="text" # will enter text into a field or value
name="name"
#string to automatically enter into the field.
#if not present will prompt the user for one
value="examplestringEGUserName"

# OTHER SUPPORTED METHODS OF ENTERING INFORMATION INTO FIELDS
# Its highly recommended not to store passwords in plaintext!!!
[[ACTION]]  
action= "text"
name = "password"
#when this is set it will utilize your operating systems keyring to securely store and access a password 
#the format for the keyrings value is [username, *keyring-service] *supported backends are   
#   "secretservice":SecretService.Keyring, #for both Kwallet on KDE and libsecret in GNOME
#   "kwallet":kwallet.DBusKeyring, #for Kwallet on linux (needs D-Bus running)
#   "windows":Windows.WinVaultKeyring, #for Windows Vault keys
#   "macos":macOS.Keyring, #for MacOS keys 
#   "libsecret":libsecret.Keyring, #for gnome-keyring on linux (needs D-Bus running)
#   "bitwarden":bitwarden_keyring #for Bitwarden. (All platforms)
#The stored password is based off the URL and the passed username
#During the first run of this config you will be prompted to enter the password into the respective field[s]
#In order to change the set keyring password pass in the argument -R during initialization 
keyring=["YourUserName"]  



[[ACTION]]
#moves to a new page with a specified href by the href url
action= "move"
href= "href_url"    

[[ACTION]]
#moves to a new page with a specified ID value
action= "move"
id= "ID" 
