#Format for The logging
{ 
  version: 1,
  formatters: {
    simple: {
      format: "%(levelname)-8s - %(message)s"
    },
    complex: {
      format: "%(levelname)-8s | %(asctime)s | PID=%(process)d | %(filename)s:%(lineno)s [%(name)s]: %(message)s"
    }
  },
  handlers: {
    stdout: {
      class: "logging.StreamHandler",
 #     level: "DEBUG",
      formatter: "complex",
      stream: "ext://sys.stdout"
    },
    stderr: {
      class: "logging.StreamHandler",
      formatter: "complex",
      stream: "ext://sys.stderr"
    },

    logfile: {
      class: "logging.handlers.RotatingFileHandler", 
      formatter: "complex", 
      maxBytes: 20000000,
      backupCount: 10,
      filename: "../../captr.log",
      mode: "w"
    }
  },
  loggers: {
  },
  root: {
    level: "INFO",
    handlers: [
      stderr,
      logfile
    ]
  },
}