[NETWORK]
SSID="examplewifi" 
URL="https://example.com" 
IP="1.0.0.1"

[[ACTION]] 
action="click"
id="example" 


[[ACTION]]
action="click"
x-path="/html/body/div/div/main/div/p[81]"
#### WILL THROW ERROR CANNOT have more than 1
id=""


[[ACTION]]
name="examplename" 


[[ACTION]]
action="click"
type="checkbox"

[[ACTION]]
action="wait"
wait=30

[[ACTION]]
action="text"
name="name"


[[ACTION]]
action="text" 
name="name"
value="examplestringEGUserName"


[[ACTION]]  
action= "text"
name = "password"
keyring=true  

[[ACTION]]
action= "move"
href= "href_url"    

[[ACTION]]
action= "move"
id= "ID" 
