name: Capture-GithubActions-Testing
on: [push]
jobs: 
  Capture-Minimal:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.12.2'
    - name: CD build
      run: docker buildx build -t dockerarch -f .github/Dockerfile .
    - name: Create Container
      run: cd .github && docker create --name dockerarch dockerarch
    - name: Copy Working Directory to Container
      run: docker cp . dockerarch:/.   
    - name: Docker 
      run: docker start dockerarch 
   
