name: Capture-GithubActions-Testing
on: [push]
jobs: 
  Capture-Minimal:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.12.2'
    - name: CD build
      run: cd .github && docker buildx build -t dockerarch -f .github .
    - name: Create Container
      run: cd .github && docker create --name dockerarch Dockerfile
    - name: Copy Working Directory to Container
      run: docker cp . dockerarch:/.
    - name: Start Docker Image 
      run: docker start dockerarch
   
