name: Type-Tests
on: 
  workflow_dispatch:
  push:
jobs: 
  mypy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.12.2'
    - name: install requirements
      run: pip install -r requirements.txt
    - name: install types
      run: mypy ./Captr/ --install-types --non-interactive
    - name: mypy test
      run: mypy ./Captr/

      