name: Type-Tests
on: 
  workflow_dispatch:
  push:
jobs: 
  mypy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Download and extract image
      uses: actions/download-artifact@v4
      with:
        name: dockerarch-image
        run: docker load -i dockerarch.tar
    - name: Copy Working Directory to Container
      run: docker cp . dockerarch:/.
    - name: Start Detatched Docker Image 
      run: docker start -d dockerarch