name: Unit-and-Integration-Tests
on: 
  workflow_dispatch:
  push:
jobs: 
  pytest-Tests:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.12.2'
    - name: install Firefox
      run: sudo apt-get install -y firefox 
    - name: Build Testing Server
      run: docker buildx build -t dockernet:dockernet -f .github/DockerNet/Dockerfile .
    - name: Run Testing Server
      run: cd .github/DockerNet && docker run -d -p 5000:5000 --name dockernet dockernet:dockernet && cd ../..
    - name: install requirements
      run: pip install -r requirements.txt
    - name: install playwright
      run: playwright install
    - name: pytest run
      run: pytest -vv
      
